version: 0.2

phases:
 install:
   runtime-versions:
     java: corretto17
   commands:
     - echo Installing Maven...
     - curl -s https://apache-mirror.rbc.ru/pub/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz | tar xz
     - echo $HOME
     - export PATH=$PATH:$HOME/apache-maven-3.6.3/bin
 pre_build:
   commands:
     - echo Log in to Amazon ECR...
     - $(aws ecr get-login --no-include-email --region us-east-1)
     - REPOSITORY_URI=373169706564.dkr.ecr.us-east-1.amazonaws.com/aws-ecs-docker
     - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
     - IMAGE_TAG=${COMMIT_HASH:=latest}
 build:
   commands:
     - echo Build started on `date`
     - echo Building the Docker image...
     - docker build -t $REPOSITORY_URI:latest .
     - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
 post_build:
   commands:
     - echo Build completed on `date`
     - docker push $REPOSITORY_URI:latest
     - docker push $REPOSITORY_URI:$IMAGE_TAG
     - echo Writing image definitions file...
     - printf '[{"name":"exp-code-pipeline","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
 files: imagedefinitions.json
